baseurl = "https://uuconf2020.rbind.io/"
languageCode = "en"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
title = "2020 Uncoast Unconf"
theme = "vex-hugo"

[params]
  description = ""

  # Put your custom stylesheets and scripts
  custom_stylesheets = []
  custom_scripts = []

  # Additional meta
  [[params.meta]]
    name = ""
    description = ""

  # Navigation bar informations
  [params.navbar]
    logo = "#uncoastUnconf"
    [[params.navbar.menu]]
      link = "/"
      text = "HOME"
    [[params.navbar.menu]]
      link = "/#about"
      text = "ABOUT"
    [[params.navbar.menu]]
      #link = "/#sponsors"
      link = "/#sponsors"
      text = "SPONSORS"
#    [[params.navbar.menu]]
#      link = "http://bit.ly/uncoastUnconf19"
#      text = "APPLY"
    [[params.navbar.menu]]
      link = "mailto:benjamin.crary@gmail.com"
      text = "CONTACT"
    [[params.navbar.menu]]
      link = "https://github.com/uncoast-unconf/uu-2020/wiki/Code-of-Conduct" # temp. work-around until I figure out the internal linking thing.
      text = "CODE OF CONDUCT"
    [[params.navbar.menu]]
      link = "https://github.com/uncoast-unconf/uu-2020/wiki/FAQ" # update with 2020
      text = "FAQ"

  # Header
  [params.header]
    title = "The 2020 Uncoast Unconference"
    text = "Bringing R users and developers together in flyover country.<br>Check out our [work](https://github.com/uncoast-unconf/uu-2019) from 2019 and start thinking of ideas for 2020!<br><br>April 16 - April 18, 2020 in Minneapolis."
    [params.header.image]
      path = "images/logo2020.png"
      alt = "Uncoastal"
#    [params.header.button]
#      link = "http://bit.ly/uncoastUnconf19" # in draft status rn.
#      text = "Apply here!"
      # want button to have color #135FB2 and color #BEC0C3 on hover

  # about
  [params.call_to_action]
    title = "Seeking sponsors for 2020!"
    text = "If you have questions about sponsorship or your organization is interested in becoming a sponsor for 2020, please email Ben Crary at benjamin.crary@gmail.com. Another thanks to our past sponsors."
    directory = "images/sponsors"
    images = ["dash.png", "UMNlib.PNG", "limnotech.png", "MinneAnalytics.png"]
  [params.promo]
    title = "What is an unconference?"
    text = "Unlike a conference with scheduled sessions and the mere hope of future collaboration, at an unconference, the collaboration happens in real time! Modeled on <a href='https://ropensci.org/blog/2018/06/05/unconf18/' style='color: #fff;text-decoration:underline;'>rOpenSci unconfs</a>, at the Uncoast Unconf, R users and developers of all different backgrounds and levels will come together for two days to collaborate on exciting data science projects. In addition, we will be hosting a Day 0 workshop for participants who are new to package development and collaboration with Github. For more on this type of unconference, see <a href='https://ropensci.org/blog/2017/11/17/unconf-sixtips/' style='color: #fff;text-decoration:underline;'>this post</a><br><br>\"The Uncoast Unconf was the most productive professional development activity I've ever done.\" - Karsten Maurer."
    [params.promo.image]
      path = "images/uuconf2019_working.png"
      alt = "What is an unconf?"
      text = "2019 Uncoast Unconf at John Deere Financial. <br><br>Photo credit: Alexa Earlywine"
  [params.features]
    title = "About"
    [params.features.image]
      path = "images/uunconfmap.png"
      alt = "Location"
    # Menu at the left of the image
    [[params.features.right]]
      icon = "tf-calendar2"
      title = "When"
      text = "April 16-18, 2020"
    [[params.features.right]]
      icon = "tf-map2"
      title = "Where"
      text = "[Wilson Research Collaboration Studio](https://www.lib.umn.edu/wilsonstudio) - Univeristy of Minnesota - Minneapolis, MN"
    [[params.features.right]]
      icon = "tf-ion-person-add"
      title = "Who"
      text = "You!"
    [[params.features.right]]
      icon = "tf-alarmclock"
      title = "Deadline to Apply"
      text = "March 4th"
    # Menu at the right of the image
    [[params.features.left]]
      icon = "tf-ion-calendar"
      title = "Day 0"
      text = "An optional 'Day Zero' workshop for learning how to write R packages and collaborate with Github. Led by Amelia McNamara and Ian Lyttle."
    [[params.features.left]]
      icon = "tf-ion-calendar"
      title = "Day 1"
      text = "Start with some introductions, form project groups, and go!"
    [[params.features.left]]
      icon = "tf-ion-calendar"
      title = "Day 2"
      text = "Continue to work on projects, group discussions, report out, dinner as a group."
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Participants"
    # How would you describe your participants? What are they bringing to your event
    text = "Our participants will represent the wide variety of skills and experience of all R users, from beginners to developers. They will represent the industry, academia, and government. We are proud to bring  a diverse group of R users and developers together in the middle of America."
    directory = "images/team"
    # All team member's pictures should be stored under 'static/img/team'.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
  [params.gallery]
    title = "Other Unconfs Past & Future"
    subtitle = "Thanks to Alexa Earlywine for the photos of the 2019 Uncoast Unconf! See more "
    link = "https://uuconf.rbind.io/"
    linktext = "here."
    text = "Be sure to check out our sister unconference, the Chicago R Collaborative, happening in March."
    # Set the image directory to use as base
    directory = "images/showcase"
    # Set the images to show in the gallery
    images = [ "uunconf2019_1.png", "uunconf2019_2.png", "uunconf2019_group.png", "uunconf2019_3.png", "uunconf2019_4.png", "uunconf2019_5.png"]
  [params.testimonials]
    title = "Organizers"
    [[params.testimonials.blocks]]
      text = "Ben  holds an MS in environmental engineering from UW Madison and currently works for LimnoTech in St. Paul, MN. He specializes in environmental statistics and data visualization."
      name = "Ben Crary"
      position = "Environmental Engineer, LimnoTech"
      image = "images/team/ben-crary.png"
    [[params.testimonials.blocks]]
      text = "Sam earned her PhD in Statistics from Iowa State University in 2017 and is currently a Science and Technology Fellow with the Bureau of Labor Statistics. The Uncoast Unconf exists because of her ideas and hard work! Check out her interests at her <a href='https://sctyner.github.io/'>website</a>."
      name = "Sam Tyner"
      position = "AAAS Science Policy Fellow, Bureau of Labor Statistics"
      image = "images/team/sam-headshot.png"
    [[params.testimonials.blocks]]
      text = "Ethan is an open science & free software enthusiast with a background in statistics education.  His current passions are <a href = 'https://github.com/statisfactions/simpr'>simulating data</a> to support educational researchers in their decision-making, when he is not busy writing <a href= 'https://soundcloud.com/tnt-yow/plotting-ihaka'>Valentine's Day songs for R.</a>."
      name = "Ethan Brown"
      position = "Research Associate, University of Minnesota"
      image = "images/team/ethan-headshot.png"
#    [params.testimonials.button]
#     link = "http://bit.ly/uncoastUnconf19"
#      text = "Apply here!"

  # Footer uses navbar data
  [params.dayzero]
    title = "Day Zero Leaders"
    [[params.dayzero.blocks]]
      text = "Amelia is a professor of statistics in the Department of Computer & Information Sciences at the University of St Thomas. Her research interests include statistics education, statistical computing, data visualization, and spatial statistics."
      name = "Amelia McNamara"
      position = "Professor of Statistics, University of St. Thomas"
      image = "images/team/Amelia_TidyverseDress.png"
    [[params.dayzero.blocks]]
      text = "Ian works as a data scientist at Schneider Electric in Cedar Rapids, Iowa. His computing interests include data visualization, interactivity, and learning different ways to think about programming and workflows."
      name = "Ian Lyttle"
      position = "Distinguished Technical Expert, Schneider Electric"
      image = "images/team/ian-headshot.png"
#    [params.testimonials.button]
#     link = "http://bit.ly/uncoastUnconf19"
#      text = "Apply here!"

  # Footer uses navbar data
  # Footer uses navbar data
  [params.newapps]
    title = "Applications"
    text = "Applications have closed. Decisions will be made by March 11."
