baseurl = ""
languageCode = "en"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
title = "Uncoast Unconf"
theme = "vex-hugo"

[params]
  description = ""

  # Put your custom stylesheets and scripts
  custom_stylesheets = []
  custom_scripts = []

  # Additional meta
  [[params.meta]]
    name = ""
    description = ""

  # Navigation bar informations
  [params.navbar]
    logo = "#uncoastUnconf"
    [[params.navbar.menu]]
      link = "/"
      text = "HOME"
    [[params.navbar.menu]]
      link = "/#about"
      text = "ABOUT"
    [[params.navbar.menu]]
      link = "/#sponsors"
      text = "SPONSORS"
#    [[params.navbar.menu]]
#      link = "http://bit.ly/uncoastUnconf19"
#      text = "APPLY"
    [[params.navbar.menu]]
      link = "mailto:benjamin.crary@gmail.com"
      text = "CONTACT"
    [[params.navbar.menu]]
      link = "https://github.com/uncoast-unconf/uu-2019/wiki/Code-of-Conduct" # temp. work-around until I figure out the internal linking thing.
      text = "CODE OF CONDUCT"
    [[params.navbar.menu]]
      link = "https://github.com/uncoast-unconf/uu-2019/wiki/FAQ" # update with 2020
      text = "FAQ"

  # Header
  [params.header]
    title = "The Uncoast Unconference"
    text = "Bringing R users and developers together in flyover country.<br>Check out our [work](https://github.com/uncoast-unconf/uu-2019) from 2019 and start thinking of ideas for 2020!"
    [params.header.image]
      path = "images/templogo.png"
      alt = "Uncoastal"
#    [params.header.button]
#      link = "http://bit.ly/uncoastUnconf19" # in draft status rn.
#      text = "Apply here!"
      # want button to have color #135FB2 and color #BEC0C3 on hover

  # about
  [params.features]
    title = "About"
    [params.features.image]
      path = "images/map.png"
      alt = "Location"
    # Menu at the left of the image
    [[params.features.right]]
      icon = "tf-calendar2"
      title = "When"
      text = "April 2020"
    [[params.features.right]]
      icon = "tf-map2"
      title = "Where"
      text = "Minneapolis - St. Paul, MN"
    [[params.features.right]]
      icon = "tf-ion-person-add"
      title = "Who"
      text = "You!"
    [[params.features.right]]
      icon = "tf-alarmclock"
      title = "Deadline"
      text = "Applications open soon"
    # Menu at the right of the image
    [[params.features.left]]
      icon = "tf-ion-calendar"
      title = "Day 0"
      text = "An optional 'Day Zero' workshop for learning how to write R packages and collaborate with Github. More info soon."
    [[params.features.left]]
      icon = "tf-ion-calendar"
      title = "Day 1"
      text = "Start with some introductions, form project groups, and go! Full schedule TK."
    [[params.features.left]]
      icon = "tf-ion-calendar"
      title = "Day 2"
      text = "Continue to work on projects, group discussions, report out, dinner as a group. Full schedule TK."

  [params.promo]
    title = "What is an unconference?"
    text = "Unlike a conference with scheduled sessions and the mere hope of future collaboration, at an unconference, the collaboration happens in real time! Modeled on <a href='https://ropensci.org/blog/2018/06/05/unconf18/' style='color: #fff;text-decoration:underline;'>rOpenSci unconfs</a>, at the Uncoast Unconf, R users and developers of all different backgrounds and levels will come together for two days to collaborate on exciting data science projects. In addition, we will be hosting a Day 0 workshop for participants who are new to package development and collaboration with Github. For more on this type of unconference, see <a href='https://ropensci.org/blog/2017/11/17/unconf-sixtips/' style='color: #fff;text-decoration:underline;'>this post</a>"
    [params.promo.image]
      path = "images/karthik-runconf17.png"
      alt = "What is an unconf?"
      text = "Photo credit: Karthik Ram, <a href='https://ropensci.org/' style='color: #fff;text-decoration:underline;'>rOpenSci</a>"

  #Test applications
  [params.applications]
    title = "What is a test?"
    text = "Unlike a conference with scheduled sessions and the mere hope of future collaboration, at an unconference, the collaboration happens in real time! Modeled on <a href='https://ropensci.org/blog/2018/06/05/unconf18/' style='color: #fff;text-decoration:underline;'>rOpenSci unconfs</a>, at the Uncoast Unconf, R users and developers of all different backgrounds and levels will come together for two days to collaborate on exciting data science projects. In addition, we will be hosting a Day 0 workshop for participants who are new to package development and collaboration with Github. For more on this type of unconference, see <a href='https://ropensci.org/blog/2017/11/17/unconf-sixtips/' style='color: #fff;text-decoration:underline;'>this post</a>"
    [params.applications.image]
      path = "images/karthik-runconf17.png"
      alt = "What is an unconf?"
      text = "Photo credit: Karthik Ram, <a href='https://ropensci.org/' style='color: #fff;text-decoration:underline;'>rOpenSci</a>"



  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Participants"
    # How would you describe your participants? What are they bringing to your event
    text = "Our participants will represent the wide variety of skills and experience of all R users, from beginners to developers. They will represent the industry, academia, and government. We are proud to bring  a diverse group of R users and developers together in the middle of America."
    directory = "images/team"
    # All team member's pictures should be stored under 'static/img/team'.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.

  [params.gallery]
    title = "Other Unconfs Past & Future"
    subtitle = "If you're in the Chicago area, also check out our sister event happening in March, the"
    link = "https://chirunconf.github.io/"
    linktext = "Chicago R Unconference."
    text = "Thanks to Mauro Lepore and Nistara Randhawa for the photos from previous rOpenSci Unconferences!"
    # Set the image directory to use as base
    directory = "images/showcase"
    # Set the images to show in the gallery
    images = ["ropensci-unconf17-checkers-nistara-randhawa.png", "mauro-runconf18-1.png", "mauro-runconf18-5.png", "mauro-runconf18-2.png", "mauro-runconf18-3.png", "mauro-runconf18-6.png", "mauro-runconf18-7.png"]

  [params.call_to_action]
    title = "Seeking sponsors for 2020!"
    text = "If you have questions about sponsorship or your organization is interested in becoming a sponsor for 2020, please email Ben Crary at benjamin.crary@gmail.com. Another thanks to our past sponsors."
    directory = "images/sponsors"
    images = ["csafe.png", "johndeere.PNG", "rstudio.png", "rconsortium.png", "schneider.png", "microsoft.png"]


  [params.testimonials]
    title = "Organizers"
    [[params.testimonials.blocks]]
      text = "Ben  holds an MS in environmental engineering from UW Madison and currently works for LimnoTech in St. Paul, MN. He specializes in environmental statistics and data visualization."
      name = "Ben Crary"
      position = "Environmental Engineer, LimnoTech"
      image = "images/ben-crary.png"
    [[params.testimonials.blocks]]
      text = "Sam earned her PhD in Statistics from Iowa State University in 2017 and is currently a Science and Technology Fellow with the Bureau of Labor Statistics. The Uncoast Unconf exists because of her ideas and hard work! Check out her interests at her <a href='https://sctyner.github.io/'>website</a>."
      name = "Sam Tyner"
      position = "Postdoc Research Associate, Iowa State University"
      image = "images/sam-headshot.png"
    [[params.testimonials.blocks]]
      text = "Ethan is an open science & free software enthusiast with a background in statistics education.  His current passions are <a href = 'https://github.com/statisfactions/simpr'>simulating data</a> to support educational researchers in their decision-making, when he is not busy writing <a href= 'https://soundcloud.com/tnt-yow/plotting-ihaka'>Valentine's Day songs for R.</a>."
      name = "Ethan Brown"
      position = "Research Assistant, University of Minnesota"
      image = "images/ethan-headshot.png"
#    [params.testimonials.button]
#     link = "http://bit.ly/uncoastUnconf19"
#      text = "Apply here!"

  # Footer uses navbar data
